### ISSUE TITLE
wp post delete on custom post type 

### ISSUE THREAD

**Issue by smazur** [wp-cli/entity-command#128]
Hi! Recently I found annoying issue with `wp post delete` command. I tried to trash some woocommerce products using this command and found that products where deleted completely from database instead. After digging into source code I found that this command uses `wp_delete_post` with `$force_delete` parameter. This parameter is very specific and works as expected only for 'post' and 'page' post types and for custom post types `$force_delete` doesn't have effect and they are always deleted by force.

I believe this is quite deceiving and leads to unexpected behavior. Please fix.

**Comment by schlessera** [comment]
We could investigate building our own trash/delete logic, instead of relying on the default `wp_delete_post()` behavior of WordPress Core.

However, that would mean that we would also trash post types that are not meant to be trashed, which could introduce bugs into existing plugins that never make that distinction... How would we know what CPTs properly support trashed posts?

**Comment by smazur** [comment]
Not sure, but maybe it would be better to add explicit `wp post trash` to force CPTs go to trash and leave `wp post delete` as is. One thing is make docs more descriptive regarding delete to trash politics.

**Comment by swissspidy** [comment]
I sorta ran into this the other day.

After running `wp post delete <id>` in a loop in a bash script, the posts were successfully deleted. The script was interrupted so I started it again. Suddenly, some of the posts were permanently deleted, which was totally unexpected.

As described here, the culprit is in `wp_delete_post()`.

**Comment by swissspidy** [comment]
Makes sense. Ran into this again yesterday, with attachments.

Note that attachments support trashing when you set `MEDIA_TRASH` to true.

**Comment by emgk** [comment]
@schlessera could you please list out the supported post types?
