### ISSUE TITLE
wp user update gets any parameter and don't throw error/warning

### ISSUE THREAD

**Issue by SanketChodavadiya** [wp-cli/entity-command#242]
I have run following command

`wp user update admin --role_userasdf=administrator`
`Success: Updated user 1.`

Is't there some warning to show?

**Comment by danielbachhuber** [comment]
Hi @SanketChodavadiya,

Thanks for the issue. `wp user update` simply passes all supplied arguments through to `wp_user_update()`. Because `wp_user_update()` theoretically could accept a `role_userasdf` argument (possibly handled by a custom action callback), it would be incorrect for WP-CLI to throw an error.
