### ISSUE TITLE
`wp post list --post_status="draft"` returns published posts if they're sticky

### ISSUE THREAD

**Issue by rob006** [wp-cli/entity-command#278]
![88b58446](https://user-images.githubusercontent.com/5972388/69906162-5e4ce380-13bf-11ea-8a9f-08dcd8d9f64e.png)

First 4 posts are sticky posts. Two of them are public - they should no be returned by command if `--post_status="draft"` filter is enabled.

**Comment by Sidsector9** [comment]
Hi @rob006 , thanks for reporting this.

It does seem that it is intentional if we consider the `ignore_sticky_posts` option, but at the same time I couldn't find any document stating sticky posts will be returned for all post statuses. I've raised it on Trac [here](https://core.trac.wordpress.org/ticket/55207), let's wait to hear back from the Core Team.

For now, you can use the following command:
`wp post list --post_status="draft" --ignore_sticky_post`
