### ISSUE TITLE
Error when inserting user passwords with special characterts 

### ISSUE THREAD

**Issue by leac** [wp-cli/entity-command#335]
When I try to create a user with a strong passwords that includes special characters (!@#$%^&*) I get an error.  

For example, this command:

`wp user create herum cloud@gmail.com --role=administrator -user_pass=e)FTjJz;K3XSH1dWDsWk#H:SSDmwu{FRef)As5w#%oE3S%$Vgwfq~8IW7TC! --allow-root`

Generates this error:

`bash: syntax error near unexpected token `)'   `

**Comment by chesio** [comment]
It's because `bash` (your command line interpreter) treats certain characters as special (see for example this [article](https://www.howtogeek.com/439199/15-special-characters-you-need-to-know-for-bash/)). You have to either escape this characters using '\' or use `'` to mark the beginning and end of the password (that way `bash` knows the password string should be interpreted literally):

```bash
wp user create herum cloud@gmail.com --role=administrator -user_pass='e)FTjJz;K3XSH1dWDsWk#H:SSDmwu{FRef)As5w#%oE3S%$Vgwfq~8IW7TC!' --allow-root
```

**Comment by leac** [comment]
Thank you very much, using `'` to mark the beginning and end of the password is a great solution
